services:

  postgres:
    image: postgres:16
    container_name: bcb-postgres
    restart: always
    environment:
      POSTGRES_DB: bcb
      POSTGRES_USER: admin_bcb
      POSTGRES_PASSWORD: bcb2026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_bcb -d bcb"]
      interval: 5s
      timeout: 5s
      retries: 10


  api:
    build: .
    container_name: bcb-api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bcb
      SPRING_DATASOURCE_USERNAME: admin_bcb
      SPRING_DATASOURCE_PASSWORD: bcb2026
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker

volumes:
  postgres_data:
